### ISSUE TITLE
When is PNG+XML export supported

### ISSUE THREAD

**Issue by KSSW** [wswartzendruber/pgs4net#1]
Hell,owswartzendruber
Hope to support PNG+XML

Releases windows

**Comment by wswartzendruber** [comment]
"Hell, owswartzendruber"?

This isn't hell, or at least I don't think it is, and I'm not owswartzendruber.

As for when PGS4NET supports PNG+XML, that _could_ happen sometime after it can do basic things, like compose display sets into captions. Or I might decide that PNG+XML export isn't within scope and make a separate utility library that does this. Or I might leave it to someone else to make a PNG+XML library using PGS4NET.

This sort of thing is barely on my radar at this point.

**Comment by KSSW** [comment]
I'm sorry, I don't know what this means. Okay, thank you
